version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8083:8000"
    env_file:
      - ./backend/.env
    restart: always
    container_name: backend
    labels:
      - traefik.enable=true
      - coolify.applicationId=2
      - coolify.name=backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:80"
    restart: always
    container_name: frontend
    labels:
      - traefik.enable=true
      - coolify.applicationId=2
      - coolify.name=frontend
