services:
  backend:
    build:
      context: ./backend
    ports:
      - "8083:8000"
    env_file:
      - ./backend/.env
    restart: always
    container_name: backend
    labels:
      - traefik.enable=true
      - coolify.applicationId=2
      - coolify.name=backend

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3002:80"
    restart: always
    container_name: frontend
    labels:
      - traefik.enable=true
      - coolify.applicationId=2
      - coolify.name=frontend
