version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8082:8000"
    environment:
      - ENV=production
    # volumes:
    #   - ./backend:/app
    restart: unless-stopped

  frontend:
  build:
    context: ./frontend
    args:
      VITE_API_URL: ${VITE_API_URL}
  ports:
    - "3001:80"
  depends_on:
    - backend
  environment:
    - NODE_ENV=production
  restart: unless-stopped

