services:
  backend:
    build:
      context: ./backend
    ports:
      - "8083:8000"
    environment:
      - ENV=production
      - CORS_ORIGINS=${CORS_ORIGINS}
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3002:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    env_file:
      - .env
