CORRECTIONS = {
    "quebec": "quedé",
    "que de": "quedé",
    "quede": "quedé",
    "para la tarde": "por la tarde",
    "ve": "quedé",
    "ede": "quedé",
    "ver": "quedé",
    "las medianas": "las Meanas",
    "las mañanas": "las Meanas",    
    "y media": "30",
    "y cuarto": "15",
    "pagina": "pág.",
    "paginas": "pág.",
    "página": "pág.",
    "páginas": "pág.",
    "ejercicio": "ej:",
    "ejercicios": "ej:",
    "a las dos": "2",
    "de las dos": "2",
    "en las dos": "2",
}
