CORRECTIONS = {
    "a las dos": "2",
    "ajena": "pág.",
    "compa que": "con Paqui",
    "compac y": " con Paqui",
    "compañia": "con Paqui a",
    "compacta": "con Paqui",
    "combatí": "con Paqui",
    "compartí": "quede con Paqui",
    "compartía": "con Paqui a",
    "comunican": "con Monica",
    "de las dos": "2",
    "de veces": "deberes",
    "Débiles": "Deberes",
    "ede": "quedé",
    "eddy": "quedé",
    "ejercicio": "ej:",
    "ejercicios": "ej:",
    "el mario": "el Atrio",
    "en las lianas": "en las Meanas",
    "en las peanas": "en las Meanas",
    "en las dos": "2",
    "johan": "Joan",
    "johann": "Joan",
    "joanne": "Joan",
    "las mañanas": "las Meanas",
    "las medianas": "las Meanas",
    "le compartí": "quede con Paqui",
    "menos cuarto": "menos 15",
    "minutos": "",
    "pagina": "pág.",
    "paginas": "pág.",
    "página": "pág.",
    "páginas": "pág.",
    "para la tarde": "por la tarde",
    "quebec": "quedé",
    "que de": "quedé",
    "quede": "quedé",
    "ver": "quedé",
    "ve": "quedé",
    "y cuarto": "15",
    "y media": "30",
    "con barcos": "con Marcos",
}
